[package]
name = "rust_dungeon"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.27.0"
env_logger = "0.11.3"
log = "0.4.21"
nalgebra = "0.32.5"
rand = "0.8.5"
unicode-width = "0.1.11"
